### ISSUE TITLE
Como utilizar onChange

### ISSUE THREAD

**Issue by gustavo-silveira** [react-brasil/forum#4]
Senhores, estou com esse problema, como posso resolver ? Estou querendo trocar a variavel de acordo com o meu objeto

`  Line 405:  Parsing error: Unexpected token, expected "}"

  403 |             id='calendarIdaVolta'
  404 |             name='calendarIdaVolta'
> 405 |             onChange={this.state[item.variavel]=> {
      |                                                ^
  406 |               this.setState({
  407 |                 date: date
  408 |               });`

Objeto 
` const map = {
      dateOne: {
        stateKey: 'date',
        variavel: date,
        handler: this.onCalendarOne,
      },
      dateTwo: {
        stateKey: 'date2',
        variavel: date,
        handler: this.onCalendarTwo,
      }
    };
    const item = map[name];`

Obrigado

**Comment by nicholasess** [comment]
@gustavo-silveira, esse ```this.state[item].variavel```é uma função? por que a estrutura pra onChange é a ```onChange={()=> {})```

**Comment by gustavo-silveira** [comment]
Esse 'this.state[item].variavel' do objeto 

    const map = {
      dateOne: {
        stateKey: 'date',
        variavel: date,
        handler: this.onCalendarOne,
      },
      dateTwo: {
        stateKey: 'date2',
        variavel: date,
        handler: this.onCalendarTwo,
      }
    };

A estrutura onChange está assim 

onChange={this.state[item.variavel]=> {
              this.setState({
                date: date
              });
            }}

**Comment by nicholasess** [comment]
@gustavo-silveira qual é a intenção desse código? ai fica mais fácil de te guiar

**Comment by gustavo-silveira** [comment]
A intenção é mudar a variavel "date"  que está no onchange de acordo com a variavel "variavel" do objeto "map". No objeto "map" a variável "variavel" estão iguais, mas seria date1 e date 2. 
O correto é mudar a variavel de acordo com o a chamada, "dateOne" ou "dateTwo"

Como posso fazer essa mudança de variavel ?

**Comment by nic** [comment]
```js
const map = {
  dateOne: {
    stateKey: 'date',
    variavel: date,
    handler: this.onCalendarOne,
  },
  dateTwo: {
    stateKey: 'date2',
    variavel: date,
    handler: this.onCalendarTwo,
  }
};

// item pode ser "dateOne" ou "dateTwo"
function onChange(item) {
  const newState = {
    date: item.variavel
  };
  this.setState(newState);
}

//< Button onClick={()=> onChange(map.dateOne)} />
//< Button onClick={()=> onChange(map.dateTwo)} />
```

@gustavo-silveira Isso que está tentando fazer?

**Comment by nicholasess** [comment]
@gustavo-silveira resolveu a issue?
