### ISSUE TITLE
Método do Map não está Definida?!

### ISSUE THREAD

**Issue by brunopeople** [react-brasil/forum#8]
Boa tarde!! 

Estou com um projeto para de um processo seletivo. Eu estou tendo este problema, mas eu realmente não estou conseguindo entender por que isto está acontecendo e não consigo encontrar a solução para isto. Bom eu sei que o método map só funcionar com variáveis de Array, no entanto o código eu declarei uma variável chamada catalogo[] e nele está os três parametros que é preciso ser declarados ,

https://github.com/brunopeople/teste-profite/tree/brunopessoa

**Comment by JandersonConstantino** [comment]
Olá @brunopeople, é um erro no componentDidMount do arquivo `Banner.js`.
Você está acessando a propriedade "products" do arquivo `produtos.json` mas não existe essa propriedade.
O array de produtos está está em `Tenis`.
Além disso você escreveu "catalago" ao invés de "catalogo" ao passar a prop para o componente de Produtos.
E possui erros de imports também.
Boa sorte no seu teste

**Comment by brunopeople** [comment]
Ok! esta parte eu já resolvi, agora veio este erro aqui que não sei o que é ??? Eu estou querendo trazer o parametro código que vem no arquivo products.json e que apareça a imagem no Slide da interface. 
![Sem título](https://user-images.githubusercontent.com/24817323/100920964-a44cf380-34ba-11eb-83be-1ca31ce19fb2.jpg)

**Comment by JandersonConstantino** [comment]
> Ok! esta parte eu já resolvi, agora veio este erro aqui que não sei o que é ??? Eu estou querendo trazer o parametro código que vem no arquivo products.json e que apareça a imagem no Slide da interface.
> ![Sem título](https://user-images.githubusercontent.com/24817323/100920964-a44cf380-34ba-11eb-83be-1ca31ce19fb2.jpg)

Acredito que ao invés de dizer "Ok!" você quis dizer "Obrigado".
Seja educado com as pessoas que estão lhe auxiliando **de graça**.

**Comment by brunopeople** [comment]
obrigado pela ajuda!! agora, pode me ajudar neste problema agora??
